table: asset_config_changes
type: change_feed
num_rows: 200
change_feed_rules:
  operation_distribution:
    INSERT: 1
    UPDATE: 4
    DELETE: 0.1
  updatable_fields:
    - threshold_value
    - sampling_frequency
    - calibration_factor
    - alert_settings
    - operational_mode
  time_range:
    start_date: "2024-01-01"
    end_date: "2024-12-31"
  time_between_changes:
    min: 1
    max: 45
  delete_null_fields:
    - threshold_value
    - sampling_frequency
    - calibration_factor
    - alert_settings
    - operational_mode
  dlt_config:
    keys: ["config_id", "asset_id"]
    sequence_by: "change_timestamp"
columns:
  config_id: int
  asset_id: int
  parameter_name:
    type: string
    format: "THRESHOLD|SAMPLING|CALIBRATION|ALERT|MODE"
  threshold_value: float
  sampling_frequency:
    type: string
    format: "1S|5S|30S|1M|5M|15M|1H"
  calibration_factor: float
  alert_settings:
    type: string
    format: "LOW-####|HIGH-####"
  operational_mode:
    type: string
    format: "NORMAL|MAINTENANCE|TESTING|BACKUP"
  change_reason:
    type: string
    format: "OPTIMIZATION|MAINTENANCE|COMPLIANCE|ALERT_RESPONSE"
  inspector_id: int
  operation:
    type: string
    format: "INSERT|UPDATE|DELETE"
  change_timestamp: datetime 